# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CmsCategoryHotGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.BigIntegerField()),
                ('goods_id', models.BigIntegerField()),
                ('sort_id', models.IntegerField()),
            ],
            options={
                'db_table': 'cms_category_hot_goods',
            },
        ),
        migrations.CreateModel(
            name='CmsPackageGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_goods_id', models.BigIntegerField()),
                ('goods_id', models.BigIntegerField()),
                ('sort', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'cms_package_goods',
            },
        ),
    ]
