# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160113_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmsCategoryIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(verbose_name=b'\xe4\xba\x8c\xe7\xba\xa7\xe5\x88\x86\xe7\xb1\xbbID')),
                ('city', models.TextField(verbose_name=b'\xe5\x9f\x8e\xe5\xb8\x82')),
                ('is_need_all_service', models.IntegerField(verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe9\x9c\x80\xe8\xa6\x81\xe5\x85\xa8\xe9\x83\xa8\xe6\x9c\x8d\xe5\x8a\xa1\xe6\x8e\xa5\xe5\x8f\xa3')),
                ('create_date', models.IntegerField(verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4\xe6\x88\xb3')),
                ('create_uid', models.IntegerField(verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe7\x94\xa8\xe6\x88\xb7ID')),
            ],
            options={
                'db_table': 'cms_category_index',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CmsCategoryIndexAds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_index_id', models.IntegerField(verbose_name=b'\xe5\x88\x86\xe7\xb1\xbb\xe9\xa6\x96\xe9\xa1\xb5ID')),
                ('create_date', models.IntegerField(verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4\xe6\x88\xb3')),
                ('create_uid', models.IntegerField(verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe7\x94\xa8\xe6\x88\xb7ID')),
                ('adbean_id', models.IntegerField(verbose_name=b'\xe5\xb9\xbf\xe5\x91\x8a\xe7\xbb\x84ID')),
                ('sort', models.IntegerField(verbose_name=b'\xe4\xbc\x98\xe5\x85\x88\xe7\xba\xa7')),
            ],
            options={
                'db_table': 'cms_category_index_ads',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CmsCategoryIndexQuickOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quick_order_id', models.IntegerField(verbose_name=b'\xe5\xbf\xab\xe6\x8d\xb7\xe5\x85\xa5\xe5\x8f\xa3ID')),
                ('category_index_id', models.IntegerField(verbose_name=b'\xe5\x88\x86\xe7\xb1\xbb\xe9\xa6\x96\xe9\xa1\xb5ID')),
                ('create_date', models.IntegerField(verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4\xe6\x88\xb3')),
                ('create_uid', models.IntegerField(verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe7\x94\xa8\xe6\x88\xb7ID')),
                ('sort', models.IntegerField(verbose_name=b'\xe4\xbc\x98\xe5\x85\x88\xe7\xba\xa7')),
            ],
            options={
                'db_table': 'cms_category_index_quick_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CmsCategoryIndexRecommendedGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_index_id', models.IntegerField(verbose_name=b'\xe5\x88\x86\xe7\xb1\xbb\xe9\xa6\x96\xe9\xa1\xb5ID')),
                ('sort', models.IntegerField(verbose_name=b'\xe6\x8e\x92\xe5\xba\x8f')),
                ('goods_id', models.IntegerField(verbose_name=b'\xe6\x9c\x8d\xe5\x8a\xa1ID')),
                ('start_date', models.IntegerField(verbose_name=b'\xe5\xbc\x80\xe5\xa7\x8b\xe6\x97\xb6\xe9\x97\xb4\xe6\x88\xb3')),
                ('end_date', models.IntegerField(verbose_name=b'\xe7\xbb\x93\xe6\x9d\x9f\xe6\x97\xb6\xe9\x97\xb4\xe6\x88\xb3')),
                ('create_date', models.IntegerField(verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4\xe6\x88\xb3')),
                ('create_uid', models.IntegerField(verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe7\x94\xa8\xe6\x88\xb7ID')),
            ],
            options={
                'db_table': 'cms_category_index_recommended_goods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CmsProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(max_length=1000, verbose_name=b'\xe9\x97\xae\xe9\xa2\x98')),
                ('answer', models.CharField(max_length=4000, verbose_name=b'\xe7\xad\x94\xe6\xa1\x88')),
                ('sort', models.IntegerField(verbose_name=b'\xe6\x8e\x92\xe5\xba\x8f')),
            ],
            options={
                'db_table': 'cms_problem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CmsQuickOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cms_quick_name', models.CharField(max_length=255, verbose_name=b'\xe5\xbf\xab\xe6\x8d\xb7\xe5\x85\xa5\xe5\x8f\xa3\xe5\x90\x8d')),
                ('cms_quick_desc', models.CharField(max_length=255, verbose_name=b'\xe5\xbf\xab\xe6\x8d\xb7\xe5\x85\xa5\xe5\x8f\xa3\xe5\x90\x8d')),
                ('image_url', models.CharField(max_length=255, verbose_name=b'\xe5\xbf\xab\xe6\x8d\xb7\xe5\x85\xa5\xe5\x8f\xa3\xe5\x90\x8d')),
                ('background_style', models.CharField(max_length=256, verbose_name=b'\xe5\xba\x95\xe8\x89\xb2')),
                ('order_style', models.CharField(max_length=256, verbose_name=b'\xe5\x88\x86\xe7\xb1\xbb\xe5\x90\x8d\xe5\xba\x95\xe8\x89\xb2')),
                ('create_date', models.IntegerField(verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4\xe6\x88\xb3')),
                ('create_uid', models.IntegerField(verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe7\x94\xa8\xe6\x88\xb7ID')),
            ],
            options={
                'db_table': 'cms_quick_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CmsQuickOrderCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quick_order_id', models.IntegerField(verbose_name=b'\xe5\xbf\xab\xe6\x8d\xb7\xe5\x85\xa5\xe5\x8f\xa3ID')),
                ('category_id', models.IntegerField(verbose_name=b'\xe4\xba\x8c\xe7\xba\xa7\xe5\x88\x86\xe7\xb1\xbbID')),
                ('create_date', models.IntegerField(verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4\xe6\x88\xb3')),
                ('create_uid', models.IntegerField(verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe7\x94\xa8\xe6\x88\xb7ID')),
            ],
            options={
                'db_table': 'cms_quick_order_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CmsQuickOrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quick_order_id', models.IntegerField(verbose_name=b'\xe5\xbf\xab\xe6\x8d\xb7\xe5\x85\xa5\xe5\x8f\xa3ID')),
                ('goods_id', models.IntegerField(verbose_name=b'\xe5\x95\x86\xe5\x93\x81(\xe6\x9c\x8d\xe5\x8a\xa1)ID')),
                ('operation_desc', models.CharField(max_length=255, verbose_name=b'\xe8\xbf\x90\xe8\x90\xa5\xe6\x8f\x8f\xe8\xbf\xb0')),
                ('sort', models.IntegerField(verbose_name=b'\xe4\xbc\x98\xe5\x85\x88\xe7\xba\xa7')),
                ('create_date', models.IntegerField(verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4\xe6\x88\xb3')),
                ('create_uid', models.IntegerField(verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe7\x94\xa8\xe6\x88\xb7ID')),
            ],
            options={
                'db_table': 'cms_quick_order_goods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CmsSecKill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name=b'\xe6\xa0\x87\xe9\xa2\x98')),
                ('desc', models.CharField(max_length=1000, verbose_name=b'\xe6\x8f\x8f\xe8\xbf\xb0')),
                ('image_bcg', models.CharField(max_length=2000, verbose_name=b'\xe7\xa7\x92\xe6\x9d\x80\xe6\xb4\xbb\xe5\x8a\xa8\xe5\x9b\xbe\xe7\x89\x87')),
                ('price_desc', models.CharField(max_length=1000, verbose_name=b'\xe7\xa7\x92\xe6\x9d\x80\xe4\xbb\xb7')),
                ('price_sub_desc', models.CharField(blank=True, max_length=1000, verbose_name=b'\xe5\x8e\x9f\xe4\xbb\xb7')),
                ('image_mark', models.CharField(blank=True, max_length=1000, verbose_name=b'\xe8\xbf\x90\xe8\x90\xa5\xe6\xa0\x87\xe7\xad\xbe')),
                ('show_start_time', models.DateTimeField(verbose_name=b'\xe6\xb4\xbb\xe5\x8a\xa8\xe5\xb1\x95\xe7\xa4\xba\xe5\xbc\x80\xe5\xa7\x8b\xe6\x97\xb6\xe9\x97\xb4')),
                ('show_end_time', models.DateTimeField(verbose_name=b'\xe6\xb4\xbb\xe5\x8a\xa8\xe5\xb1\x95\xe7\xa4\xba\xe7\xbb\x93\xe6\x9d\x9f\xe6\x97\xb6\xe9\x97\xb4')),
                ('action_id', models.IntegerField(verbose_name=b'\xe5\x8a\xa8\xe4\xbd\x9cID')),
                ('share_title', models.CharField(max_length=1000, verbose_name=b'\xe5\x88\x86\xe4\xba\xab\xe6\xa0\x87\xe9\xa2\x98')),
                ('share_desc', models.CharField(max_length=2000, verbose_name=b'\xe5\x88\x86\xe4\xba\xab\xe6\x8f\x8f\xe8\xbf\xb0')),
                ('share_url', models.CharField(max_length=1000, verbose_name=b'\xe5\x88\x86\xe4\xba\xab\xe9\x93\xbe\xe6\x8e\xa5')),
                ('share_thumbnail', models.CharField(max_length=1000, verbose_name=b'\xe5\x88\x86\xe4\xba\xab\xe7\xbc\xa9\xe7\x95\xa5\xe5\x9b\xbe')),
                ('activity_id', models.IntegerField(verbose_name=b'\xe8\x90\xa5\xe9\x94\x80\xe6\xb4\xbb\xe5\x8a\xa8ID')),
                ('goods_id', models.IntegerField(verbose_name=b'\xe5\x95\x86\xe5\x93\x81ID')),
                ('city', models.CharField(max_length=2000, verbose_name=b'\xe6\xb4\xbb\xe5\x8a\xa8\xe5\x9f\x8e\xe5\xb8\x82')),
                ('tips', models.CharField(blank=True, max_length=1000, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x8f\x90\xe9\x86\x92')),
                ('seckill_remark_url', models.CharField(blank=True, max_length=1000, verbose_name=b'\xe7\xa7\x92\xe6\x9d\x80\xe8\xaf\xb4\xe6\x98\x8e')),
            ],
            options={
                'db_table': 'cms_seckill',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CmsSecKillView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.IntegerField(verbose_name=b'\xe6\xb8\xa0\xe9\x81\x93ID')),
                ('seckill_id', models.IntegerField(verbose_name=b'\xe7\xa7\x92\xe6\x9d\x80\xe9\x85\x8d\xe7\xbd\xaeID')),
                ('status', models.IntegerField(verbose_name=b'\xe7\x8a\xb6\xe6\x80\x81')),
            ],
            options={
                'db_table': 'cms_seckill_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CmsSecKillViewTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(verbose_name=b'\xe7\x8a\xb6\xe6\x80\x81')),
            ],
            options={
                'db_table': 'cms_seckill_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CmsShareCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.IntegerField()),
                ('dialog_title', models.CharField(max_length=256)),
                ('dialog_content', models.CharField(max_length=256)),
                ('dialog_img', models.CharField(blank=True, max_length=256, null=True)),
                ('button_name', models.CharField(max_length=256)),
                ('action_type', models.IntegerField()),
                ('share_imgurl', models.CharField(blank=True, max_length=256, null=True)),
                ('share_title', models.CharField(blank=True, max_length=256, null=True)),
                ('share_content', models.CharField(blank=True, max_length=256, null=True)),
                ('share_url', models.CharField(blank=True, max_length=256, null=True)),
                ('action_id', models.IntegerField(blank=True, null=True)),
                ('action_json', models.CharField(blank=True, max_length=256, null=True)),
                ('times_limit', models.IntegerField(blank=True, null=True)),
                ('start_time', models.IntegerField(blank=True, null=True)),
                ('end_time', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(max_length=256)),
                ('show_style', models.IntegerField()),
                ('icon', models.CharField(blank=True, max_length=256, null=True)),
                ('details_url', models.CharField(blank=True, max_length=256, null=True)),
                ('activity_id', models.CharField(blank=True, max_length=200, null=True)),
                ('is_dialog', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cms_share_coupon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CmsViewShareCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'cms_view_share_coupon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OpGoodsActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityId', models.IntegerField(verbose_name=b'\xe8\x90\xa5\xe9\x94\x80\xe6\xb4\xbb\xe5\x8a\xa8ID')),
                ('activityPrice', models.IntegerField(verbose_name=b'\xe8\x90\xa5\xe9\x94\x80\xe4\xbb\xb7\xe6\xa0\xbc')),
                ('price', models.IntegerField(verbose_name=b'\xe4\xbb\xb7\xe6\xa0\xbc')),
                ('applyUser', models.CharField(max_length=100)),
                ('commentCount', models.IntegerField(verbose_name=b'\xe8\xaf\x84\xe8\xae\xba\xe6\x95\xb0')),
                ('cpid', models.IntegerField(verbose_name=b'CP ID')),
                ('goodsId', models.IntegerField(verbose_name=b'\xe5\x95\x86\xe5\x93\x81ID')),
                ('gorder', models.IntegerField(verbose_name=b'gorder')),
                ('orderCount', models.IntegerField(verbose_name=b'\xe9\x94\x80\xe5\x94\xae\xe6\x95\xb0\xe9\x87\x8f')),
                ('promotionMsg', models.CharField(max_length=256, verbose_name=b'\xe6\xb4\xbb\xe5\x8a\xa8\xe6\x8f\x8f\xe8\xbf\xb0')),
                ('promotionType', models.IntegerField(verbose_name=b'\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('activityBeginDate', models.DateTimeField(verbose_name=b'\xe6\xb4\xbb\xe5\x8a\xa8\xe5\xbc\x80\xe5\xa7\x8b\xe6\x97\xb6\xe9\x97\xb4')),
                ('activityEndDate', models.DateTimeField(verbose_name=b'\xe6\xb4\xbb\xe5\x8a\xa8\xe7\xbb\x93\xe6\x9d\x9f\xe6\x97\xb6\xe9\x97\xb4')),
                ('activityCity', models.TextField(verbose_name=b'\xe6\xb4\xbb\xe5\x8a\xa8\xe6\x94\xaf\xe6\x8c\x81\xe5\x9f\x8e\xe5\xb8\x82')),
                ('rawstring', models.TextField(verbose_name=b'\xe5\xa4\x87\xe6\xb3\xa8')),
                ('updateTime', models.DateTimeField(verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('is_seckill', models.IntegerField(verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe7\xa7\x92\xe6\x9d\x80')),
                ('capacity', models.IntegerField(verbose_name=b'\xe6\xb4\xbb\xe5\x8a\xa8\xe4\xbe\x9b\xe8\xb4\xa7\xe9\x87\x8f')),
            ],
            options={
                'db_table': 'op_goods_activity_act',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OpGoodsActivityView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name=b'\xe5\x95\x86\xe5\x93\x81\xe5\x90\x8d')),
                ('cp_name', models.CharField(max_length=200, verbose_name=b'CP\xe5\x90\x8d\xe5\xad\x97')),
                ('activityId', models.IntegerField(verbose_name=b'\xe8\x90\xa5\xe9\x94\x80\xe6\xb4\xbb\xe5\x8a\xa8ID')),
                ('activityPrice', models.IntegerField(verbose_name=b'\xe8\x90\xa5\xe9\x94\x80\xe4\xbb\xb7\xe6\xa0\xbc')),
                ('price', models.IntegerField(verbose_name=b'\xe4\xbb\xb7\xe6\xa0\xbc')),
                ('applyUser', models.CharField(max_length=100)),
                ('commentCount', models.IntegerField(verbose_name=b'\xe8\xaf\x84\xe8\xae\xba\xe6\x95\xb0')),
                ('cpid', models.IntegerField(verbose_name=b'CP ID')),
                ('goodsId', models.IntegerField(verbose_name=b'\xe5\x95\x86\xe5\x93\x81ID')),
                ('gorder', models.IntegerField(verbose_name=b'gorder')),
                ('orderCount', models.IntegerField(verbose_name=b'\xe9\x94\x80\xe5\x94\xae\xe6\x95\xb0\xe9\x87\x8f')),
                ('promotionMsg', models.CharField(max_length=256, verbose_name=b'\xe6\xb4\xbb\xe5\x8a\xa8\xe6\x8f\x8f\xe8\xbf\xb0')),
                ('promotionType', models.IntegerField(verbose_name=b'\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('activityBeginDate', models.DateTimeField(verbose_name=b'\xe6\xb4\xbb\xe5\x8a\xa8\xe5\xbc\x80\xe5\xa7\x8b\xe6\x97\xb6\xe9\x97\xb4')),
                ('activityEndDate', models.DateTimeField(verbose_name=b'\xe6\xb4\xbb\xe5\x8a\xa8\xe7\xbb\x93\xe6\x9d\x9f\xe6\x97\xb6\xe9\x97\xb4')),
                ('activityCity', models.TextField(verbose_name=b'\xe6\xb4\xbb\xe5\x8a\xa8\xe6\x94\xaf\xe6\x8c\x81\xe5\x9f\x8e\xe5\xb8\x82')),
                ('rawstring', models.TextField(verbose_name=b'\xe5\xa4\x87\xe6\xb3\xa8')),
                ('updateTime', models.DateTimeField(verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('is_seckill', models.IntegerField(verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe7\xa7\x92\xe6\x9d\x80')),
                ('capacity', models.IntegerField(verbose_name=b'\xe6\xb4\xbb\xe5\x8a\xa8\xe4\xbe\x9b\xe8\xb4\xa7\xe9\x87\x8f')),
            ],
            options={
                'db_table': 'op_goods_activity_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewCmsSecKillView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.IntegerField(verbose_name=b'\xe6\xb8\xa0\xe9\x81\x93ID')),
                ('seckill_id', models.IntegerField(verbose_name=b'\xe7\xa7\x92\xe6\x9d\x80\xe9\x85\x8d\xe7\xbd\xaeID')),
                ('title', models.CharField(max_length=1000, verbose_name=b'\xe6\xa0\x87\xe9\xa2\x98')),
                ('desc', models.CharField(max_length=2000, verbose_name=b'\xe6\x8f\x8f\xe8\xbf\xb0')),
                ('image_bcg', models.CharField(max_length=2000, verbose_name=b'\xe5\x9b\xbe\xe7\x89\x87')),
                ('price_desc', models.CharField(max_length=1000, verbose_name=b'\xe7\xa7\x92\xe6\x9d\x80\xe4\xbb\xb7\xe6\xa0\xbc')),
                ('price_sub_desc', models.CharField(max_length=1000, verbose_name=b'\xe5\x8e\x9f\xe4\xbb\xb7')),
                ('image_mark', models.CharField(max_length=1000, verbose_name=b'\xe8\xbf\x90\xe8\x90\xa5\xe6\xa0\x87\xe7\xad\xbe')),
                ('show_start_time', models.DateTimeField(verbose_name=b'\xe6\xb4\xbb\xe5\x8a\xa8\xe5\xb1\x95\xe7\xa4\xba\xe5\xbc\x80\xe5\xa7\x8b\xe6\x97\xb6\xe9\x97\xb4')),
                ('show_end_time', models.DateTimeField(verbose_name=b'\xe6\xb4\xbb\xe5\x8a\xa8\xe5\xb1\x95\xe7\xa4\xba\xe7\xbb\x93\xe6\x9d\x9f\xe6\x97\xb6\xe9\x97\xb4')),
                ('city', models.CharField(max_length=2000, verbose_name=b'\xe5\x9f\x8e\xe5\xb8\x82')),
            ],
            options={
                'db_table': 'view_cms_seckills',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='cmsactivityv37',
            options={'managed': False, 'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='cmscpdisplay',
            options={'managed': False, 'ordering': ['location1']},
        ),
        migrations.AddField(
            model_name='cmsnavicategory',
            name='background',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name=b'\xe5\xba\x95\xe8\x89\xb2'),
        ),
        migrations.AddField(
            model_name='cmsnavicategory',
            name='category_index_icon',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name=b'\xe5\x88\x86\xe7\xb1\xbb\xe9\xa6\x96\xe9\xa1\xb5\xe6\xa0\x87\xe7\xad\xbe'),
        ),
        migrations.AddField(
            model_name='cmsnavicategory',
            name='category_index_remark',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name=b'\xe5\x88\x86\xe7\xb1\xbb\xe9\xa6\x96\xe9\xa1\xb5\xe6\x8f\x8f\xe8\xbf\xb0'),
        ),
        migrations.AddField(
            model_name='cmsnavicategory',
            name='type',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=b'\xe5\x88\x86\xe7\xb1\xbb\xe7\xb1\xbb\xe5\x9e\x8b'),
        ),
        migrations.AlterField(
            model_name='cmsnavicategory',
            name='location',
            field=models.IntegerField(verbose_name=b'\xe5\x88\x86\xe7\xb1\xbb\xe9\xa1\xb5\xe6\x8e\x92\xe5\xba\x8f'),
        ),
        migrations.AlterField(
            model_name='cmsnavicategory',
            name='location2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=b'\xe9\xa6\x96\xe9\xa1\xb5\xe6\x8e\x92\xe5\xba\x8f'),
        ),
    ]
