# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-29 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160728_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100, unique=True)),
                ('token', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_token',
            },
        ),
    ]
