# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TabChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.BigIntegerField(verbose_name='\u6e20\u9053id')),
            ],
            options={
                'db_table': 'cms_view_tab_config',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tabs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('un_check_name', models.CharField(max_length=20, verbose_name='uTab\u540d\u79f0')),
                ('check_name', models.CharField(max_length=20, verbose_name='Tab\u540d\u79f0')),
                ('un_check_style', models.CharField(max_length=20, verbose_name='u\u989c\u8272')),
                ('check_style', models.CharField(max_length=20, verbose_name='\u989c\u8272')),
                ('un_check_icon', models.CharField(max_length=100, verbose_name='u\u56fe\u6807')),
                ('check_icon', models.CharField(max_length=100, verbose_name='\u56fe\u6807')),
                ('action_id', models.BigIntegerField(verbose_name='\u52a8\u4f5cid')),
                ('dot_key', models.CharField(max_length=50, verbose_name='\u6253\u70b9key')),
                ('sort', models.IntegerField(default=0, verbose_name='\u6392\u5e8f')),
            ],
            options={
                'db_table': 'cms_tab_config',
                'managed': False,
            },
        ),
    ]
