# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-31 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0004_authtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelCoverAds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.IntegerField(verbose_name='\u6e20\u9053ID')),
            ],
            options={
                'db_table': 'cms_channel_cover_ads',
            },
        ),
        migrations.CreateModel(
            name='CoverAds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u540d\u79f0')),
                ('logo', models.URLField(verbose_name='\u5e7f\u544a\u56fe\u7247')),
                ('display_time', models.IntegerField(default=2, verbose_name='\u663e\u793a\u65f6\u95f4')),
                ('start_time', models.DateTimeField(verbose_name='\u5f00\u59cb\u65e5\u671f')),
                ('end_time', models.DateTimeField(verbose_name='\u7ed3\u675f\u65e5\u671f')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CmsActions')),
            ],
            options={
                'db_table': 'cms_cover_ads',
            },
        ),
        migrations.AddField(
            model_name='channelcoverads',
            name='ads',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.CoverAds'),
        ),
        migrations.AddField(
            model_name='channelcoverads',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PtYellowCitylist'),
        ),
    ]
