# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponAllotRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cids', models.CharField(max_length=255, verbose_name='\u5238ID')),
                ('cnames', models.CharField(max_length=255, verbose_name='\u5238\u540d')),
                ('count', models.IntegerField(verbose_name='\u53d1\u5238\u6570')),
                ('ucount', models.IntegerField(verbose_name='\u7528\u6237\u6570')),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u53d1\u5238\u7406\u7531')),
                ('allot_time', models.DateTimeField(auto_now_add=True, verbose_name='\u9886\u53d6\u65f6\u95f4')),
                ('c_user', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u521b\u5efa\u4eba')),
            ],
            options={
                'db_table': 'coupon_allot_record',
            },
        ),
    ]
