# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-29 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_couponallotrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponresource',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u7406\u7531'),
        ),
    ]
