# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TagBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quick_order_id', models.BigIntegerField(verbose_name='\u5feb\u6377\u5165\u53e3id')),
                ('tag_group_id', models.BigIntegerField(verbose_name='\u6807\u7b7e\u7ec4id')),
                ('level', models.BigIntegerField(default=0, verbose_name='\u6392\u5e8f')),
            ],
            options={
                'db_table': 'cms_quick_order_taggroup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TagGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_group_id', models.BigIntegerField(verbose_name='\u6807\u7b7e\u7ec4id')),
                ('tag_id', models.BigIntegerField(verbose_name='\u6807\u7b7eid')),
                ('sort', models.BigIntegerField(default=0, verbose_name='\u6392\u5e8f')),
            ],
            options={
                'db_table': 'cms_tag_group_tag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_group_name', models.CharField(max_length=100, verbose_name='\u540d\u79f0')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u63cf\u8ff0')),
            ],
            options={
                'db_table': 'cms_tag_group',
            },
        ),
        migrations.CreateModel(
            name='TagGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.BigIntegerField(verbose_name='\u5546\u54c1id')),
                ('sku_id', models.BigIntegerField(verbose_name='\u89c4\u683cid')),
                ('sort', models.BigIntegerField(default=0, verbose_name='\u6392\u5e8f')),
                ('tag_id', models.IntegerField(verbose_name='\u6807\u7b7eid')),
            ],
            options={
                'db_table': 'cms_goods_sku_tag',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='\u540d\u79f0')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5907\u6ce8')),
                ('logo', models.URLField(blank=True, null=True, verbose_name='\u6807\u7b7e\u56fe')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u63cf\u8ff0')),
            ],
            options={
                'db_table': 'cms_tag',
            },
        ),
    ]
